# Generated by Django 6.0 on 2026-01-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('process', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('register_number', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=100)),
                ('btech_percentage', models.FloatField()),
                ('inter_percentage', models.FloatField()),
                ('ssc_percentage', models.FloatField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('image', models.ImageField(upload_to='profiles/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.drive')),
            ],
        ),
    ]
