# Generated by Django 6.0 on 2026-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_posted_on_drive_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=20)),
                ('student_photo', models.ImageField(upload_to='selected_students/')),
            ],
        ),
    ]
