# Generated by Django 6.0 on 2026-01-06 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_selectedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='job_role',
            field=models.CharField(default='Software Engineer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
