# Generated by Django 6.0 on 2026-01-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_drive_job_role_drive_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='eligible_branches',
            field=models.CharField(default='CSE', max_length=255),
            preserve_default=False,
        ),
    ]
